bitstation-vdi:
	./mkimg.sh  Bitstation vdi mageia-net

bitstation-dsk:
	./mkimg.sh Bitstation dsk mageia-net-smalldsk

bitquant:
	./mkimg.sh Bitquant dsk mageia-net-smalldsk

install-deps:
	sudo ./install-deps.sh

clean:
	rm -f *-*:*:* *~
